# Generated by Django 4.1.7 on 2023-03-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_listing', '0003_studentuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='type',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='Applicant',
        ),
    ]
