# Generated by Django 4.1.4 on 2023-03-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='looking_for',
            field=models.CharField(choices=[('Remote', 'Remote'), ('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship')], default='Full Timme', max_length=30, null=True),
        ),
    ]
