# Generated by Django 4.1.7 on 2023-03-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_alter_profile_looking_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='looking_for',
            field=models.CharField(choices=[('Part Time', 'Part Time'), ('Remote', 'Remote'), ('Internship', 'Internship'), ('Full Time', 'Full Time')], default='Full Timme', max_length=30, null=True),
        ),
    ]
